#include <stdio.h>
#include "nodo.h"

#define NO_HAY_PELEA 0
#define HAY_PELEA 1

#define NO_ES_HOGUERA 0
#define ES_HOGUERA 1

#define NO_HAY_BRANCH 0
#define HAY_BRANCH 1

t_nodo nodos[CANT_MAX_NODOS] = {
    {
        {0, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {1, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { SOLDADO_BASICO, SOLDADO_BASICO, SOLDADO_BASICO, ENEMIGO_VACIO }, 3,
        { GOHAN, KRILLIN }, 2,
        {BOTAS, BOTAS}, 2
    },

    {
        {2, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {3, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { BANDIDOS, BANDIDOS, BANDIDOS, BANDIDOS }, 4,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {4, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {5, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { SOLDADO_BASICO, SOLDADO_BASICO, SOLDADO_BASICO, SOLDADO_BASICO }, 4,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {6, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {7, 8},HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {8, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {9, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { BESTIAS_DE_LA_NIEBLA, BESTIAS_DE_LA_NIEBLA, ENEMIGO_VACIO, ENEMIGO_VACIO }, 2,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {10, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {11, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {12, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {13, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { GUARDIAN, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 1,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {14, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { GUARDIAN_FASE_DOS, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 1,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {15, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {16, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { SOLDADO_FREEZER_ELITE, SOLDADO_FREEZER_ELITE, SOLDADO_FREEZER_ELITE, ENEMIGO_VACIO }, 3,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {17, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {18, 0}, NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { GOLEM_NAMEKIANO, GOLEM_NAMEKIANO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 2,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {19, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {20, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {21, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {22, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { HOLOGRAMA_DE_FREEZER, SOLDADOS_INTERMEDIOS, SOLDADOS_INTERMEDIOS, ENEMIGO_VACIO }, 3,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {23, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}
    },
    {
        {24, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {25, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {26, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { BANDIDOS, BANDIDOS, BANDIDOS, BANDIDOS }, 4,
        { GOHAN, KRILLIN }, 2,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
        {
        {27, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
        {
        {28, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
        {
        {29, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {30, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { SOLDADOS_SAIYAJIN, SOLDADOS_SAIYAJIN, SOLDADOS_SAIYAJIN, SOLDADOS_SAIYAJIN }, 4,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {31, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { VEGETA_ENEMIGO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 1,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {32, 33}, HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {33, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {34, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO }, 3,
        {ITEM_VACIO, ITEM_VACIO}
    },
    {
        {35, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO, VEGETA }, 4,
        {ITEM_VACIO, ITEM_VACIO}
    },
    {
        {0, 0},NO_HAY_BRANCH, ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOHAN, KRILLIN, PICCOLO, VEGETA }, 4,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {36, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { JHEESE, BULTA, RACOOM, GINEW }, 4,
        { GOHAN, KRILLIN, PICCOLO, VEGETA }, 4,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {37, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { FREEZER, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 1,
        { GOKU }, 1,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {38, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        HAY_PELEA, { FREEZER, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 1,
        { GOKU_SSJ }, 1,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {39, 40},HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOKU_SSJ }, 1,
        {ITEM_VACIO, ITEM_VACIO}, 0
    },
    {
        {40, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOKU_SSJ }, 1,
        {ITEM_VACIO, ITEM_VACIO}
    },
    {
        {41, 0},NO_HAY_BRANCH, NO_ES_HOGUERA,
        NO_HAY_PELEA, { ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO, ENEMIGO_VACIO }, 0,
        { GOKU_SSJ }, 1,
        {ITEM_VACIO, ITEM_VACIO}
    },

};


unsigned int cargar_nodos(t_nodo* nodo)
{

}
